### ISSUE TITLE
turn inlay hints on by default?

### ISSUE THREAD

**Issue by damccull** [nvim-lua/kickstart.nvim#948]
I just updated to the most recent commit for kickstart.nvim and I'm happy to see a toggle now for inlay hints.

However, I want it on by default and able to be toggled off. I understand the `<leader>th` keymap will toggle to the inverse of the current state, so I tried adding this to my init.lua near my `vim.opt`s.

```lua
-- Enable inlay hints by default; toggle off with <leader>th
vim.lsp.inlay_hint.enable()
```

The toggle will still work if I toggle it twice (I'm assuming the first one is setting it to 'off' after my code messes up the state), but I can't get it to default on. How do I fix this?

**Comment by eljamm** [comment]
How about adding it like this, instead?

```lua
if client and client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
  -- Toggle inlay hints
  map('<leader>th', function()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
  end, '[T]oggle Inlay [H]ints')

  -- Enable inlay hints by default
  vim.lsp.inlay_hint.enable()
end
```

This way, inlay hints will be on by default and you can toggle them with `<leader>th`

**Comment by damccull** [comment]
Oh, wow. That's great, thanks. Exactly what I was trying to do and in a much better way.

**Comment by damccull** [comment]
Well, I thought this should work, but inlay hints are not enabling until I toggle it twice, still. Am I using the enable() function wrong?

**Comment by damccull** [comment]
Ok, so it _does_ seem to be activating inlay hints. However, they aren't showing up until something in the code changes. If I force rust_analyzer to reevaluate the code by changing whitespace above or below where I should see an inlay, for instance, it shows up. Otherwise I need to toggle it twice. Is there an additional code I need to make it display them automatically without needing to change something or manually toggle it twice?

**Comment by eljamm** [comment]
I'm using [rustaceanvim](https://github.com/mrcjkb/rustaceanvim) and it works normally.

I guess the issue you're describing is related to [this](https://github.com/neovim/neovim/issues/26511), which rustaceanvim is working around [here](https://github.com/mrcjkb/rustaceanvim/blob/a73e8618d8518b2a7434e1c21e4da4e66f21f738/lua/rustaceanvim/server_status.lua#L14).

**Comment by sergeken** [comment]
Would be great to have a commented section with 

>
-- Remove comment to enable inlay hints by default
-- vim.lsp.inlay_hint.enable()

**Comment by dffuller** [comment]
It appears some of this code made it into the last release. 
``` lua
if client and client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
  -- Toggle inlay hints
  map('<leader>th', function()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
  end, '[T]oggle Inlay [H]ints')

  -- Enable inlay hints by default
  vim.lsp.inlay_hint.enable()
end
```
 When I go through diagnostic errors in a (basically) new kickstart.nvim file, I am getting an error  stating "This function requires 1 argument but instead it is receiving 0 for the is_enabled() call.  The diagnostic error goes away when I add a table `{ bufnr = 0}` inside the call, but I'm not sure this is what is desired.

Edit: It looks like you can just drop the parens after is_enabled.  They seem to be throwing the diagnostic error.

**Comment by eljamm** [comment]
Curious why that doesn't work for you considering that's how it's written in the [Neovim docs](https://neovim.io/doc/user/lsp.html#lsp-inlay_hint). It still works for me, but deleting the parens works as well.

Is it a difference in versions? I'm using Neovim v0.10.0

**Comment by dffuller** [comment]
I, too, am using v0.10.0.  I can't say for certain that it "doesn't work" but I was getting diagnostic errors for the issue.

**Comment by eljamm** [comment]
Oh, that's just a warning not an error, so you can safely ignore it. I didn't see it before because I had turned off some neodev diagnostics.

It's worth noting that I thought removing the parens worked at first, but with that the toggle only works once, then it stops working. Replacing the parens with curly braces worked, though, and the warning disappeared as well:

```lua
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled {})
```

Don't know what the ramifications of this is are, though.

**Comment by VlaDexa** [comment]
> I was getting diagnostic errors for the issue.

[This was a neovim docs issue](https://github.com/neovim/neovim/issues/29230)

**Comment by feoh** [comment]
Fixed in a recent merge.

**Comment by VlaDexa** [comment]
Not quite fixed (because the initial issue wasn't a bug, more of a question), but I think it's overall resolved apart from the neovim issue.

**Comment by PNDTG** [comment]
Hi, I'm using nvim, nvchad config, and rustaceanvim, and I'm a total newbie, migrating from vscode.
I'm using nvim v0.10.4
on Windows 11
and this is at the end of my init.lua file related to rustaceanvim:
```lua
  {
    'mrcjkb/rustaceanvim',
    version = '^5',
    lazy = false,
    ["rust_analyzer"] = {
      cargo = {
        allFeatures = true,
      },
      checkOnSave = {
        command = "clippy",
      },
    },
  },
```
But the script you provided is not working... I've tried many different scripts and even wrote something myself but nothing actually shows the inlay hints. I checked out the issue you linked but that seems to be about inlayHints becoming enabled before rust-analyzer server. But that should be fixed if I just toggle inlayHints on and off... but it's not doing anything.

![Image](https://github.com/user-attachments/assets/2889a1c7-5702-4375-bb15-c26d13e2c9e7)

**Comment by PNDTG** [comment]
Fixed it...
Wow... apparently the issue was `inlay_hint.enable()`
You have to give `true` as an argument... it was not giving me an error about this at all... but now that I put `inlay_hint.enabled(true)` it's working all fine... I'm just shocked at how simple this issue was.
